# Generated by Django 5.2.9 on 2025-12-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tercero', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_respondiente', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('respuestas_data', models.JSONField(default=dict)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='empresas.empresacliente')),
            ],
        ),
    ]
