"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'empresas',
    'formularios',
    'dashboard',

    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co' # Español de Colombia

TIME_ZONE = 'America/Bogota' # <--- ESTO ES LO IMPORTANTE

USE_I18N = True
USE_TZ = True


# ==========================================
# GESTIÓN DE ARCHIVOS (LOCAL vs AWS)
# ==========================================

# 1. Rutas Base (Siempre necesarias para Local y para collectstatic)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Donde Django recolecta archivos

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Donde se guardan subidas en local

# 2. El "Interruptor": Leemos si estamos en modo S3
USE_S3 = os.environ.get('USE_S3') == 'True'

if USE_S3:
    # -------------------------------------
    # CONFIGURACIÓN PRODUCCIÓN (AWS S3)
    # -------------------------------------
    
    # Librerías necesarias solo en producción
    INSTALLED_APPS += ['storages']

    # Configuración AWS
    AWS_STORAGE_BUCKET_NAME = 'vadomdata'
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_DEFAULT_ACL = None
    
    # Prefijo del Cliente (Dinámico por servidor)
    S3_CLIENT_PREFIX = os.environ.get('S3_CLIENT_PREFIX', 'default')

    # Dominio de S3
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    # Definición de Storages (Django 4.2+)
    STORAGES = {
        "default": {
            "BACKEND": "core.storages.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "core.storages.StaticStorage",
        },
    }

    # Sobreescribimos URLs para que apunten a S3
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_CLIENT_PREFIX}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{S3_CLIENT_PREFIX}/media/'

else:
    # -------------------------------------
    # CONFIGURACIÓN LOCAL (Tu PC)
    # -------------------------------------
    
    # Usamos el almacenamiento estándar de archivos
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # En local no hacemos nada más, usa STATIC_ROOT y MEDIA_ROOT definidos arriba.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# REDIRECCIONES DE LOGIN
LOGIN_URL = 'login'             # Si no estás logueado, te manda aquí
LOGIN_REDIRECT_URL = '/'        # <--- CAMBIO: Al entrar, vas a la raíz (Dashboard)
LOGOUT_REDIRECT_URL = 'login'   # Al salir, vuelves al login


# CONFIGURACIÓN DE AUTENTICACIÓN
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',  # Nuestro backend personalizado (Usuario O Email)
    'django.contrib.auth.backends.ModelBackend', # El default de Django (por seguridad)
]


# TIEMPO DE EXPIRACIÓN DE SESIÓN (En segundos)
# Ejemplo: 30 minutos = 30 * 60 = 1800 segundos
SESSION_COOKIE_AGE = 1800 

# Para que la sesión expire al cerrar el navegador (Opcional, pero recomendado)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# IMPORTANTE: Esto hace que el reloj se reinicie con cada clic
# Si el usuario navega, el tiempo vuelve a contar desde cero.
# Si deja la pantalla quieta 30 min, se cierra.
SESSION_SAVE_EVERY_REQUEST = True