"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=lambda v: [s.strip() for s in v.split(',')])

CSRF_TRUSTED_ORIGINS = [
    'https://encuestas.vadomsystems.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'empresas',
    'formularios',
    'dashboard',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co' # Español de Colombia

TIME_ZONE = 'America/Bogota' # <--- ESTO ES LO IMPORTANTE

USE_I18N = True
USE_TZ = True


# ==========================================
# GESTIÓN DE ARCHIVOS (GLOBAL Y PRODUCCIÓN)
# ==========================================

# 1. ¿Dónde están mis archivos locales? (¡LA LÍNEA QUE FALTABA!)
# Esto le dice a Django: "Busca también en la carpeta 'static' al lado de manage.py"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 2. Definiciones Base (Django las necesita siempre)
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / 'media'


# 3. Lógica de Almacenamiento (S3 vs Local)
if not DEBUG:
    # ---------------------------------------------------------
    # CONFIGURACIÓN AWS S3 (Producción - Privado con Firmas)
    # ---------------------------------------------------------
    INSTALLED_APPS += ['storages']

    AWS_STORAGE_BUCKET_NAME = 'vadomdata'
    AWS_S3_REGION_NAME = 'us-east-1'
    
    # IMPORTANTE: Sin Custom Domain para que fuerce la firma completa
    # AWS_S3_CUSTOM_DOMAIN = ... (Comentado)
    
    # --- SEGURIDAD ---
    AWS_DEFAULT_ACL = None  # Evita error 500 (Bucket Owner Enforced)
    AWS_QUERYSTRING_AUTH = True  # ¡CRÍTICO! Firma las URLs para ver archivos privados
    
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_FILE_OVERWRITE = False

    S3_PREFIX = 'encuestas_gf'

    from storages.backends.s3boto3 import S3Boto3Storage

    class StaticStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/static'
        default_acl = None

    class MediaStorage(S3Boto3Storage):
        location = f'{S3_PREFIX}/media'
        file_overwrite = False
        default_acl = None

    # URLs Base (Boto3 se encargará de rellenar el dominio y la firma)
    STATIC_URL = f'/static/'
    MEDIA_URL = f'/media/'

    STORAGES = {
        "default": {"BACKEND": "core.settings.MediaStorage"},
        "staticfiles": {"BACKEND": "core.settings.StaticStorage"},
    }

else:
    # ---------------------------------------------------------
    # CONFIGURACIÓN LOCAL (Desarrollo)
    # ---------------------------------------------------------
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

# REDIRECCIONES DE LOGIN
LOGIN_URL = 'login'             # Si no estás logueado, te manda aquí
LOGIN_REDIRECT_URL = '/'        # <--- CAMBIO: Al entrar, vas a la raíz (Dashboard)
LOGOUT_REDIRECT_URL = 'login'   # Al salir, vuelves al login


# CONFIGURACIÓN DE AUTENTICACIÓN
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',  # Nuestro backend personalizado (Usuario O Email)
    'django.contrib.auth.backends.ModelBackend', # El default de Django (por seguridad)
]


# TIEMPO DE EXPIRACIÓN DE SESIÓN (En segundos)
# Ejemplo: 30 minutos = 30 * 60 = 1800 segundos
SESSION_COOKIE_AGE = 1800 

# Para que la sesión expire al cerrar el navegador (Opcional, pero recomendado)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# IMPORTANTE: Esto hace que el reloj se reinicie con cada clic
# Si el usuario navega, el tiempo vuelve a contar desde cero.
# Si deja la pantalla quieta 30 min, se cierra.
SESSION_SAVE_EVERY_REQUEST = True