# Generated by Django 5.2.9 on 2025-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('slug', models.SlugField(help_text='Identificador único para la URL', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('color_primario', models.CharField(default='#000000', max_length=7)),
                ('email_soporte', models.EmailField(max_length=254)),
                ('tiene_sagrilaft', models.BooleanField(default=True, verbose_name='Activar Bloque SAGRILAFT')),
                ('tiene_ptee', models.BooleanField(default=False, verbose_name='Activar Bloque PTEE')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
