# Generated by Django 5.2.9 on 2025-12-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='aliado',
            field=models.CharField(choices=[('GFR', 'Gestión Financiera de Riesgos'), ('LEGAL_SHIELD', 'Legal Shield')], default='GFR', max_length=20, verbose_name='Firma Consultora (Aliado)'),
        ),
    ]
