# Generated by Django 5.2.9 on 2025-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresacliente_aliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='tiene_sarlaft',
            field=models.BooleanField(default=False),
        ),
    ]
