# Generated by Django 5.2.9 on 2026-01-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresacliente_tiene_sarlaft'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='config_encuesta',
            field=models.JSONField(blank=True, default=None, help_text='JSON con tipos de tercero, campos y preguntas adicionales', null=True, verbose_name='Configuración personalizada de encuesta'),
        ),
    ]
