# Generated by Django 5.2.9 on 2026-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_config_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacliente',
            name='solo_superadmin',
            field=models.BooleanField(default=False, help_text='Si está activo, esta empresa solo la ve y gestiona el superusuario', verbose_name='Solo para Superadmin'),
        ),
    ]
